### ISSUE TITLE
Cursor go to the end of input at each keypress

### ISSUE THREAD

**Issue by guillaume-gagnaire** [eight04/custom-input#3]
Hi !

When i use your datetime angularjs module, after typing the first digit of the date, the cursor goes at the end of the input. So I have to click again on first digit to continue filling the date ...

I use : 

Custom-input v0.2.0
angular-datetime-input v5.1.0
AngularJS 1.5.3
Angular Material 1.1.0

**Comment by eight04** [comment]
Does it happen on the [demo](https://rawgit.com/eight04/angular-datetime/master/example/demo-1.5.html) too? Which browser can reproduce the bug, or all?

**Comment by eight04** [comment]
Also, is this bug related to Angular Material? If so, could you provide the directive you used?

**Comment by guillaume-gagnaire** [comment]
Thanks for your reply,

I use the code in the <md-input-container> directive : 

`<md-input-container class="md-block">
                    <input type="text"
                           datetime="dd/MM/yyyy"
                           datetime-model="yyyy-MM-dd"
                           ng-required="item.required"
                           ng-model="replies[$index]" />
</md-input-container>`

The bug is on the latest version of Google Chrome, maybe there is a conflict between custom-input and Angular Material ? Dunno.

**Comment by eight04** [comment]
I created a plunker with Angular Material, but I couldn't reproduce the bug. [Here](http://plnkr.co/edit/rrYTCa7eHhwsDTrFI6H1?p=preview)
Chrome 57.0.2987.98 (64-bit)

Since I never use Angular Material, maybe I did something wrong in the plunker.

If it only occurs on chrome, could it cause by the extensions or other script?

**Comment by guillaume-gagnaire** [comment]
Curious ! I'll continue searching by my side, thanks by the way !
