### ISSUE TITLE
Angular exemple

### ISSUE THREAD

**Issue by maximepvrt** [eight04/custom-input#4]
Can you create a simple angular exemple or an angular version ?
During one day, I was try :(

It's my directive : https://plnkr.co/edit/89ixk8hX16bjafgbSipx?p=preview

Big thanks :-) @eight04

**Comment by eight04** [comment]
[There is a demo](https://rawgit.com/eight04/custom-input/master/demo.html) which showcase how to build a `TextParser`, and link the parser and the element with `InputMask`. If you need an example which attaches `TextParser`/`InputMask` to Angular's digest loop, checkout [angular-datetime](https://github.com/eight04/angular-datetime/blob/master/lib/directive.js).

Also, in your plunker `input-duration` is misspelled as `inupt-duration`.
